# Generated by Django 3.2.25 on 2025-03-12 21:55

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20250309_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.unit_image_file_path),
        ),
    ]
